# AB-DB tutorial: finding, downloading, visualizing and retrieving analysis
***

This Jupyter Notebook will guide you through the process of **finding**, **downloading**, **visualizing** and finally **retrieving analysis results** from the collection of **AB-DB** ligands **MD simulations** and **QM data** available in the **[AB-DB](https://mmb.irbbarcelona.org/ABDB/) database**.

This workflow is based on the **AB-DB database REST API**: https://mmb.irbbarcelona.org/ABDB/rest

Main **AB-DB website**: https://mmb.irbbarcelona.org/ABDB/

***Authors:*** *Giuliano Malloci, Silvia Gervasoni, Adam Hospital, Genís Bayarri*
<br>
***Version:*** *July 2026*

***
## Tutorial steps
 1. [Libraries and Global Variables](#libraries)
 2. [Listing AB-DB Compounds](#listing)
 3. [Browsing AB-DB Database](#browsing)
 4. [Searching & Finding in the AB-DB Database](#searching)
 5. [Physico-chemical descriptors from AB-DB](#descriptors)
 6. [MD data from AB-DB](#md)
    - *Structure downloading*
    - *Structure visualization*
    - *Trajectory downloading*
    - *Trajectory visualization*
    - *Trajectory analyses (MDDB<sup>1</sup>)*
 7. [QM data from AB-DB](#qm)
    - *Download the QM-optimized structure and compare it against the original one*
    - *AMBER force-field parameters generated from the QM calculations*
    - *Geometry optimization and Single-point energy calculation data (ioChem-BD<sup>2</sup>)*
 8. [Questions & Comments](#questions)


<sup>1</sup> https://mdposit.mddbr.eu/
<br>
<sup>2</sup> https://www.iochem-bd.org/
***

<div style="text-align:center;">
<img src="https://upload.wikimedia.org/wikipedia/commons/d/de/Logo_Universit%C3%A0_di_Cagliari.jpg" alt="University of Cagliari logo"
	title="University of Cagliari logo" width="150" style="margin-right: 20px; align: center"/>
<img src="https://mmb.irbbarcelona.org/ABDB/img/home/irb.png" alt="IRB logo"
	title="IRB logo" width="250" style="margin-left: 20px;"/>
</div>

***

In [1]:
# Only executed when using google colab
import sys
import os
if 'google.colab' in sys.modules:

  try:
      from google.colab import output as _colab_output
      _colab_output.enable_custom_widget_manager()  # must precede nglview import
      get_ipython().run_line_magic('pip', 'install -q "nglview==3.0.8" mdtraj py3Dmol rich')
  except ImportError:
      pass  # not running in Colab

<a id="libraries"></a>
## Libraries and Global Variables

In [2]:
# Auxiliary libraries

import urllib.request
import json
import os
from math import floor, ceil
from os.path import exists
from urllib.parse import quote

import ipywidgets
import nglview
#import simpletraj

import pandas as pd

#import plotly
#import plotly.graph_objs as go
#plotly.offline.init_notebook_mode(connected=True)

from rich import print
from rich.panel import Panel

In [3]:
# URLs to the REST APIs and Web Servers

web_url = 'https://mmb.irbbarcelona.org/ABDB'
api_url = f'{web_url}/api'

mddb_web = 'https://mdposit.mddbr.eu/'

iochem_bd_web = 'https://iochem-bd.org/'

<a id="listing"></a>
## Listing AB-DB Compounds
Listing the **AB-DB collection compounds**.

Exposing the **AB-DB persistent id (FAIR_ID)**, **compound**, **charge**, **family**, **formula**, **inchikey**, **pubchem** and **MDDB accession**.

In [4]:
compounds_request = f'{api_url}/compounds?limit=1000'

# Query the API
with urllib.request.urlopen(compounds_request) as response:
    parsed_response = json.loads(response.read().decode("utf-8"))

print(json.dumps(parsed_response['data'], indent=2))

[
  {
    "FAIR_ID": "ABDB001001",
    "Family": "aminocoumarins",
    "Compound": "chlorobiocin",
    "Formula": "C35H36ClN2O11",
    "Charge": -1,
    "accession": "MD-A007LC",
    "inchikey": "FJAQNRBDVKIIKK-LFLQOBSNSA-M",
    "pubchem": "90657643"
  },
  {
    "FAIR_ID": "ABDB001002",
    "Family": "aminocoumarins",
    "Compound": "declovanillobiocin",
    "Formula": "C31H31N2O12",
    "Charge": -1,
    "accession": "MD-A007LZ",
    "inchikey": "JURYCYSCKRZQLD-UHFFFAOYSA-N",
    "pubchem": "76173558"
  },
  {
    "FAIR_ID": "ABDB001003",
    "Family": "aminocoumarins",
    "Compound": "isovanillobiocin",
    "Formula": "C31H30ClN2O12",
    "Charge": -1,
    "accession": "MD-A007M0",
    "inchikey": "AKYRQFMQZJFLAE-UHFFFAOYSA-N",
    "pubchem": "76181969"
  },
  {
    "FAIR_ID": "ABDB001004",
    "Family": "aminocoumarins",
    "Compound": "novclobiocin_101",
    "Formula": "C35H37N2O11",
    "Charge": -1,
    "accession": "MD-A007M1",
    "inchikey": "GMMYCBAAMDJSHV-YQQRZDPSSA-M",
    "pubchem": "90659375"
  },
  {
    "FAIR_ID": "ABDB001005",
    "Family": "aminocoumarins",
    "Compound": "novobiocin",
    "Formula": "C31H35N2O11",
    "Charge": -1,
    "accession": "MD-A007M2",
    "inchikey": "DYYIUCVAQGRACE-UHFFFAOYSA-N",
    "pubchem": "4546"
  },
  {
    "FAIR_ID": "ABDB001006",
    "Family": "aminocoumarins",
    "Compound": "plazomicin",
    "Formula": "C25H53N6O10",
    "Charge": 5,
    "accession": "MD-A007M3",
    "inchikey": "IYDYFVUFSPQPPV-UHFFFAOYSA-N",
    "pubchem": "74821141"
  },
  {
    "FAIR_ID": "ABDB001007",
    "Family": "aminocoumarins",
    "Compound": "ribostamycin",
    "Formula": "C17H37N4O10",
    "Charge": 3,
    "accession": "MD-A007M4",
    "inchikey": "NSKGQURZWSPSBC-VVPCINPTSA-Q",
    "pubchem": "52358477"
  },
  {
    "FAIR_ID": "ABDB001008",
    "Family": "aminocoumarins",
    "Compound": "ribostamycin",
    "Formula": "C17H38N4O10",
    "Charge": 4,
    "accession": "MD-A007M5",
    "inchikey": "NSKGQURZWSPSBC-VVPCINPTSA-R",
    "pubchem": "51035374"
  },
  {
    "FAIR_ID": "ABDB001009",
    "Family": "aminocoumarins",
    "Compound": "vanillobiocin",
    "Formula": "C31H30ClN2O12",
    "Charge": -1,
    "accession": "MD-A007M6",
    "inchikey": "LNDDBMXOCFEELJ-UHFFFAOYSA-N",
    "pubchem": "76180016"
  },
  {
    "FAIR_ID": "ABDB002001",
    "Family": "aminoglycosides",
    "Compound": "amikacin",
    "Formula": "C22H46N5O13",
    "Charge": 3,
    "accession": "MD-A007N7",
    "inchikey": "LKCWBDHBTVXHDL-UHFFFAOYSA-N",
    "pubchem": "2142"
  },
  {
    "FAIR_ID": "ABDB002002",
    "Family": "aminoglycosides",
    "Compound": "amikacin",
    "Formula": "C22H47N5O13",
    "Charge": 4,
    "accession": "MD-A007N8",
    "inchikey": "LKCWBDHBTVXHDL-RMDFUYIESA-R",
    "pubchem": "90657305"
  },
  {
    "FAIR_ID": "ABDB002003",
    "Family": "aminoglycosides",
    "Compound": "apramycin",
    "Formula": "C21H45N5O11",
    "Charge": 4,
    "accession": "MD-A007N9",
    "inchikey": "XZNUGFQTQHRASN-UHFFFAOYSA-N",
    "pubchem": "439519"
  },
  {
    "FAIR_ID": "ABDB002004",
    "Family": "aminoglycosides",
    "Compound": "arbekacin",
    "Formula": "C22H48N6O10",
    "Charge": 4,
    "accession": "MD-A007NA",
    "inchikey": "MKKYBZZTJQGVCD-UHFFFAOYSA-N",
    "pubchem": "2226"
  },
  {
    "FAIR_ID": "ABDB002005",
    "Family": "aminoglycosides",
    "Compound": "arbekacin",
    "Formula": "C22H49N6O10",
    "Charge": 5,
    "accession": "MD-A007NB",
    "inchikey": "MKKYBZZTJQGVCD-XTCKQBCOSA-S",
    "pubchem": "90658692"
  },
  {
    "FAIR_ID": "ABDB002006",
    "Family": "aminoglycosides",
    "Compound": "dibekacin",
    "Formula": "C18H41N5O8",
    "Charge": 4,
    "accession": "MD-A007NC",
    "inchikey": "JJCQSGDBDPYCEO-UHFFFAOYSA-N",
    "pubchem": "3021"
  },
  {
    "FAIR_ID": "ABDB002007",
    "Family": "aminoglycosides",
    "Compound": "dibekacin",
    "Formula": "C18H42N5O8",
    "Charge": 5,
    "accession": "MD-A007ND",
    "inchikey": "JJCQSGDBDPYCEO-XVZSLQNASA-S",
    "pubchem": "51432348"
  },
  {
    "FAIR_ID": "ABDB002008",
    "Family": "aminoglycosides",
    "Compound": "gentamicin",
    "Formula": "C21H47N5O7",
    "Charge": 4,
    "accession": "MD-A007NE",
    "inchikey": "CEAZRRDELHUEMR-UHFFFAOYSA-N",
    "pubchem": "3467"
  },
  {
    "FAIR_ID": "ABDB002009",
    "Family": "aminoglycosides",
    "Compound": "hygrovetine",
    "Formula": "C20H39N3O13",
    "Charge": 2,
    "accession": "MD-A007NF",
    "inchikey": "GRRNUXAQVGOGFE-UHFFFAOYSA-N",
    "pubchem": "3659"
  },
  {
    "FAIR_ID": "ABDB002010",
    "Family": "aminoglycosides",
    "Compound": "hygrovetine",
    "Formula": "C20H40N3O13",
    "Charge": 3,
    "accession": "MD-A007NG",
    "inchikey": "GRRNUXAQVGOGFE-UHFFFAOYSA-Q",
    "pubchem": "74413801"
  },
  {
    "FAIR_ID": "ABDB002011",
    "Family": "aminoglycosides",
    "Compound": "isepamicin",
    "Formula": "C22H47N5O12",
    "Charge": 4,
    "accession": "MD-A007NH",
    "inchikey": "UDIIBEDMEYAVNG-UHFFFAOYSA-N",
    "pubchem": "3755"
  },
  {
    "FAIR_ID": "ABDB002012",
    "Family": "aminoglycosides",
    "Compound": "kanamycin",
    "Formula": "C18H39N4O11",
    "Charge": 3,
    "accession": "MD-A007NI",
    "inchikey": "SBUJHOSQTJFQJX-UHFFFAOYSA-Q",
    "pubchem": "44273327"
  },
  {
    "FAIR_ID": "ABDB002013",
    "Family": "aminoglycosides",
    "Compound": "kanamycin",
    "Formula": "C18H40N4O11",
    "Charge": 4,
    "accession": "MD-A007NJ",
    "inchikey": "SBUJHOSQTJFQJX-NOAMYHISSA-R",
    "pubchem": "25200943"
  },
  {
    "FAIR_ID": "ABDB002014",
    "Family": "aminoglycosides",
    "Compound": "neomycin",
    "Formula": "C23H51N6O13",
    "Charge": 5,
    "accession": "MD-A007NK",
    "inchikey": "PGBHMTALBVVCIT-UHFFFAOYSA-S",
    "pubchem": "44273313"
  },
  {
    "FAIR_ID": "ABDB002015",
    "Family": "aminoglycosides",
    "Compound": "neomycin",
    "Formula": "C23H52N6O13",
    "Charge": 6,
    "accession": "MD-A007NL",
    "inchikey": "PGBHMTALBVVCIT-VCIWKGPPSA-T",
    "pubchem": "23278715"
  },
  {
    "FAIR_ID": "ABDB002016",
    "Family": "aminoglycosides",
    "Compound": "netilmicin",
    "Formula": "C21H45N5O7",
    "Charge": 4,
    "accession": "MD-A007NM",
    "inchikey": "CIDUJQMULVCIBT-MQDUPKMGSA-R",
    "pubchem": "52354867"
  },
  {
    "FAIR_ID": "ABDB002017",
    "Family": "aminoglycosides",
    "Compound": "netilmicin",
    "Formula": "C21H46N5O7",
    "Charge": 5,
    "accession": "MD-A007NN",
    "inchikey": "CIDUJQMULVCIBT-UHFFFAOYSA-N",
    "pubchem": "4460"
  },
  {
    "FAIR_ID": "ABDB002018",
    "Family": "aminoglycosides",
    "Compound": "paromomycin",
    "Formula": "C23H49N5O14",
    "Charge": 4,
    "accession": "MD-A007NO",
    "inchikey": "UOZODPSAJZTQNH-UHFFFAOYSA-R",
    "pubchem": "44273057"
  },
  {
    "FAIR_ID": "ABDB002019",
    "Family": "aminoglycosides",
    "Compound": "paromomycin",
    "Formula": "C23H50N5O14",
    "Charge": 5,
    "accession": "MD-A007NP",
    "inchikey": "UOZODPSAJZTQNH-LSWIJEOBSA-S",
    "pubchem": "92136216"
  },
  {
    "FAIR_ID": "ABDB002020",
    "Family": "aminoglycosides",
    "Compound": "sisomicin",
    "Formula": "C19H41N5O7",
    "Charge": 4,
    "accession": "MD-A007NQ",
    "inchikey": "URWAJWIAIPFPJE-YFMIWBNJSA-R",
    "pubchem": "52416107"
  },
  {
    "FAIR_ID": "ABDB002021",
    "Family": "aminoglycosides",
    "Compound": "sisomicin",
    "Formula": "C19H42N5O7",
    "Charge": 5,
    "accession": "MD-A007NR",
    "inchikey": "URWAJWIAIPFPJE-UHFFFAOYSA-N",
    "pubchem": "5224"
  },
  {
    "FAIR_ID": "ABDB002022",
    "Family": "aminoglycosides",
    "Compound": "spectinomycin",
    "Formula": "C14H25N2O7",
    "Charge": 1,
    "accession": "MD-A007NS",
    "inchikey": "UNFWWIHTNXNPBV-WXKVUWSESA-O",
    "pubchem": "146014739"
  },
  {
    "FAIR_ID": "ABDB002023",
    "Family": "aminoglycosides",
    "Compound": "spectinomycin",
    "Formula": "C14H26N2O7",
    "Charge": 2,
    "accession": "MD-A007NT",
    "inchikey": "UNFWWIHTNXNPBV-WXKVUWSESA-P",
    "pubchem": "11870427"
  },
  {
    "FAIR_ID": "ABDB002024",
    "Family": "aminoglycosides",
    "Compound": "streptomycin",
    "Formula": "C21H42N7O12",
    "Charge": 3,
    "accession": "MD-A007NU",
    "inchikey": "UCSJYZPVAKXKNQ-HZYVHMACSA-Q",
    "pubchem": "25245365"
  },
  {
    "FAIR_ID": "ABDB002025",
    "Family": "aminoglycosides",
    "Compound": "tobramycin",
    "Formula": "C18H41N5O9",
    "Charge": 4,
    "accession": "MD-A007NV",
    "inchikey": "NLVFBUXFDBBNBW-UHFFFAOYSA-R",
    "pubchem": "44273325"
  },
  {
    "FAIR_ID": "ABDB002026",
    "Family": "aminoglycosides",
    "Compound": "tobramycin",
    "Formula": "C18H42N5O9",
    "Charge": 5,
    "accession": "MD-A007NW",
    "inchikey": "NLVFBUXFDBBNBW-PBSUHMDJSA-S",
    "pubchem": "51432351"
  },
  {
    "FAIR_ID": "ABDB003001",
    "Family": "anthracenediones",
    "Compound": "mitoxantrone",
    "Formula": "C22H30N4O6",
    "Charge": 2,
    "accession": "MD-A007OZ",
    "inchikey": "KKZJGLLVHKMTCM-UHFFFAOYSA-P",
    "pubchem": "24848320"
  },
  {
    "FAIR_ID": "ABDB003002",
    "Family": "anthracenediones",
    "Compound": "pixantrone",
    "Formula": "C17H21N5O2",
    "Charge": 2,
    "accession": "MD-A007P0",
    "inchikey": "PEZPMAYDXJQYRV-UHFFFAOYSA-P",
    "pubchem": null
  },
  {
    "FAIR_ID": "ABDB004001",
    "Family": "anthracyclines",
    "Compound": "daunorubicin",
    "Formula": "C27H30NO10",
    "Charge": 1,
    "accession": "MD-A007R0",
    "inchikey": "STQGQHZAVUOBTE-VGBVRHCVSA-O",
    "pubchem": "7067174"
  },
  {
    "FAIR_ID": "ABDB004002",
    "Family": "anthracyclines",
    "Compound": "doxorubicin",
    "Formula": "C27H30NO11",
    "Charge": 1,
    "accession": "MD-A007R1",
    "inchikey": "AOJJSUZBOXZQNB-TZSSRYMLSA-O",
    "pubchem": "40469134"
  },
  {
    "FAIR_ID": "ABDB004003",
    "Family": "anthracyclines",
    "Compound": "epirubicin",
    "Formula": "C27H30NO11",
    "Charge": 1,
    "accession": "MD-A007R2",
    "inchikey": "AOJJSUZBOXZQNB-VTZDEGQISA-O",
    "pubchem": "5288078"
  },
  {
    "FAIR_ID": "ABDB004004",
    "Family": "anthracyclines",
    "Compound": "idarubicin",
    "Formula": "C26H28NO9",
    "Charge": 1,
    "accession": "MD-A007R3",
    "inchikey": "XDXDZDZNSLXDNA-TZNDIEGXSA-O",
    "pubchem": "90659160"
  },
  {
    "FAIR_ID": "ABDB005001",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "avibactam",
    "Formula": "C7H10N3O6S",
    "Charge": -1,
    "accession": "MD-A007M7",
    "inchikey": "NDCUAPJVLWFHHB-UHNVWZDZSA-M",
    "pubchem": "58319026"
  },
  {
    "FAIR_ID": "ABDB005002",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "bal29880",
    "Formula": "C15H20N6O6S",
    "Charge": 0,
    "accession": "MD-A007M8",
    "inchikey": "IZHHBASEWCBSMD-NEPJUHHUSA-N",
    "pubchem": "16122922"
  },
  {
    "FAIR_ID": "ABDB005003",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "clavulanic_acid",
    "Formula": "C8H8NO5",
    "Charge": -1,
    "accession": "MD-A007M9",
    "inchikey": "HZZVJAQRINQKSD-PBFISZAISA-M",
    "pubchem": "16204478"
  },
  {
    "FAIR_ID": "ABDB005004",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "durlobactam",
    "Formula": "C8H10N3O6S",
    "Charge": -1,
    "accession": "MD-A007MA",
    "inchikey": "BISPBXFUKNXOQY-RITPCOANSA-M",
    "pubchem": "140709768"
  },
  {
    "FAIR_ID": "ABDB005005",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "enmetazobactam",
    "Formula": "C11H14N4O5S",
    "Charge": 0,
    "accession": "MD-A007MB",
    "inchikey": "HFZITXBUTWITPT-YWVKMMECSA-N",
    "pubchem": "23653540"
  },
  {
    "FAIR_ID": "ABDB005006",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "nacubactam",
    "Formula": "C9H16N4O7S",
    "Charge": 0,
    "accession": "MD-A007MC",
    "inchikey": "RSBPYSTVZQAADE-RQJHMYQMSA-N",
    "pubchem": "73386748"
  },
  {
    "FAIR_ID": "ABDB005007",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "relebactam",
    "Formula": "C12H20N4O6S",
    "Charge": 0,
    "accession": "MD-A007MD",
    "inchikey": "SMOBCLHAZXOKDQ-ZJUUUORDSA-N",
    "pubchem": "44129647"
  },
  {
    "FAIR_ID": "ABDB005008",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "sulbactam",
    "Formula": "C8H10NO5S",
    "Charge": -1,
    "accession": "MD-A007ME",
    "inchikey": "FKENQMMABCRJMK-RITPCOANSA-M",
    "pubchem": "6971136"
  },
  {
    "FAIR_ID": "ABDB005009",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "tazobactam",
    "Formula": "C10H11N4O5S",
    "Charge": -1,
    "accession": "MD-A007MF",
    "inchikey": "LPQZKKCYTLCDGQ-WEDXCCLWSA-M",
    "pubchem": "7048533"
  },
  {
    "FAIR_ID": "ABDB005010",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "thienamycin",
    "Formula": "C11H16N2O4S",
    "Charge": 0,
    "accession": "MD-A007MG",
    "inchikey": "WKDDRNSBRWANNC-ATRFCDNQSA-N",
    "pubchem": "441128"
  },
  {
    "FAIR_ID": "ABDB005011",
    "Family": "beta-lactamase-inhibitors",
    "Compound": "zidebactam",
    "Formula": "C13H21N5O7S",
    "Charge": 0,
    "accession": "MD-A007MH",
    "inchikey": "YCZPXRQPDCXTIO-BBBLOLIVSA-N",
    "pubchem": "77846445"
  },
  {
    "FAIR_ID": "ABDB006001",
    "Family": "carbapenems",
    "Compound": "biapenem",
    "Formula": "C15H18N4O4S",
    "Charge": 0,
    "accession": "MD-A007NX",
    "inchikey": "MRMBZHPJVKCOMA-YJFSRANCSA-N",
    "pubchem": "71339"
  },
  {
    "FAIR_ID": "ABDB006002",
    "Family": "carbapenems",
    "Compound": "doripenem",
    "Formula": "C15H24N4O6S2",
    "Charge": 0,
    "accession": "MD-A007NY",
    "inchikey": "AVAACINZEOAHHE-VFZPANTDSA-N",
    "pubchem": "73303"
  },
  {
    "FAIR_ID": "ABDB006003",
    "Family": "carbapenems",
    "Compound": "ertapenem",
    "Formula": "C22H24N3O7S",
    "Charge": -1,
    "accession": "MD-A007NZ",
    "inchikey": "JUZNIMUFDBIJCM-ANEDZVCMSA-M",
    "pubchem": "24848279"
  },
  {
    "FAIR_ID": "ABDB006004",
    "Family": "carbapenems",
    "Compound": "faropenem",
    "Formula": "C12H14NO5S",
    "Charge": -1,
    "accession": "MD-A007O0",
    "inchikey": "HGGAKXAHAYOLDJ-FHZUQPTBSA-M",
    "pubchem": null
  },
  {
    "FAIR_ID": "ABDB006005",
    "Family": "carbapenems",
    "Compound": "imipenem",
    "Formula": "C12H17N3O4S",
    "Charge": 0,
    "accession": "MD-A007O1",
    "inchikey": "ZSKVGTPCRGIANV-ZXFLCMHBSA-N",
    "pubchem": "104838"
  },
  {
    "FAIR_ID": "ABDB006006",
    "Family": "carbapenems",
    "Compound": "LK-157",
    "Formula": "C14H16NO4",
    "Charge": -1,
    "accession": "MD-A007O2",
    "inchikey": "ACQFJWSLWQLLIA-PLWQYUFKSA-M",
    "pubchem": "91936033"
  },
  {
    "FAIR_ID": "ABDB006007",
    "Family": "carbapenems",
    "Compound": "meropenem",
    "Formula": "C17H25N3O5S",
    "Charge": 0,
    "accession": "MD-A007O3",
    "inchikey": "DMJNNHOOLUXYBV-PQTSNVLCSA-N",
    "pubchem": "441130"
  },
  {
    "FAIR_ID": "ABDB006008",
    "Family": "carbapenems",
    "Compound": "olivanic_acid",
    "Formula": "C11H14N2O4S",
    "Charge": 0,
    "accession": "MD-A007O4",
    "inchikey": "HFTVKHFILHLXJF-UHFFFAOYSA-N",
    "pubchem": "3035450"
  },
  {
    "FAIR_ID": "ABDB006009",
    "Family": "carbapenems",
    "Compound": "panipenem",
    "Formula": "C15H21N3O4S",
    "Charge": 0,
    "accession": "MD-A007O5",
    "inchikey": "TYMABNNERDVXID-DLYFRVTGSA-N",
    "pubchem": "72015"
  },
  {
    "FAIR_ID": "ABDB006010",
    "Family": "carbapenems",
    "Compound": "razupenem",
    "Formula": "C18H21N3O4S2",
    "Charge": 0,
    "accession": "MD-A007O6",
    "inchikey": "XFGOMLIRJYURLQ-GOKYHWASSA-N",
    "pubchem": "10993211"
  },
  {
    "FAIR_ID": "ABDB006011",
    "Family": "carbapenems",
    "Compound": "ritipenem",
    "Formula": "C10H11N2O6S",
    "Charge": -1,
    "accession": "MD-A007O7",
    "inchikey": "IKQNRQOUOZJHTR-UWBRJAPDSA-M",
    "pubchem": "18596549"
  },
  {
    "FAIR_ID": "ABDB006012",
    "Family": "carbapenems",
    "Compound": "sanfetrinem",
    "Formula": "C14H18NO5",
    "Charge": -1,
    "accession": "MD-A007O8",
    "inchikey": "ICFDDEJRXZSWTA-KJFVXYAMSA-M",
    "pubchem": "155613756"
  },
  {
    "FAIR_ID": "ABDB006013",
    "Family": "carbapenems",
    "Compound": "tebipenem",
    "Formula": "C16H22N3O4S2",
    "Charge": -1,
    "accession": "MD-A007O9",
    "inchikey": "GXXLUDOKHXEFBQ-YJFSRANCSA-M",
    "pubchem": "154420694"
  },
  {
    "FAIR_ID": "ABDB006014",
    "Family": "carbapenems",
    "Compound": "tomopenem",
    "Formula": "C23H36N7O6S",
    "Charge": 1,
    "accession": "MD-A007OA",
    "inchikey": "KEDAXBWZURNCHS-GPODMPQUSA-N",
    "pubchem": "9809656"
  },
  {
    "FAIR_ID": "ABDB007001",
    "Family": "cephalosporins",
    "Compound": "cefaclor",
    "Formula": "C15H14ClN3O4S",
    "Charge": 0,
    "accession": "MD-A007P1",
    "inchikey": "QYIYFLOTGYLRGG-GPCCPHFNSA-N",
    "pubchem": "51039"
  },
  {
    "FAIR_ID": "ABDB007002",
    "Family": "cephalosporins",
    "Compound": "cefadroxil",
    "Formula": "C16H17N3O5S",
    "Charge": 0,
    "accession": "MD-A007P2",
    "inchikey": "BOEGTKLJZSQCCD-UEKVPHQBSA-N",
    "pubchem": "47965"
  },
  {
    "FAIR_ID": "ABDB007003",
    "Family": "cephalosporins",
    "Compound": "cefalonium",
    "Formula": "C20H18N4O5S2",
    "Charge": 0,
    "accession": "MD-A007P3",
    "inchikey": "FMZXNVLFJHCSAF-DNVCBOLYSA-N",
    "pubchem": "21743"
  },
  {
    "FAIR_ID": "ABDB007004",
    "Family": "cephalosporins",
    "Compound": "cefamandole_nafate",
    "Formula": "C19H17N6O6S2",
    "Charge": -1,
    "accession": "MD-A007P4",
    "inchikey": "RRJHESVQVSRQEX-SUYBPPKGSA-M",
    "pubchem": "40467085"
  },
  {
    "FAIR_ID": "ABDB007005",
    "Family": "cephalosporins",
    "Compound": "cefamandole_sodium",
    "Formula": "C18H17N6O5S2",
    "Charge": -1,
    "accession": "MD-A007P5",
    "inchikey": "OLVCFLKTBJRLHI-AXAPSJFSSA-M",
    "pubchem": "21680723"
  },
  {
    "FAIR_ID": "ABDB007006",
    "Family": "cephalosporins",
    "Compound": "cefazolin",
    "Formula": "C14H13N8O4S3",
    "Charge": -1,
    "accession": "MD-A007P6",
    "inchikey": "MLYYVTUWGNIJIB-BXKDBHETSA-M",
    "pubchem": "641385"
  },
  {
    "FAIR_ID": "ABDB007007",
    "Family": "cephalosporins",
    "Compound": "cefdinir",
    "Formula": "C14H13N5O5S2",
    "Charge": -2,
    "accession": "MD-A007P7",
    "inchikey": "CDRBTVLXEBVFKT-UHFFFAOYSA-N",
    "pubchem": "2620"
  },
  {
    "FAIR_ID": "ABDB007008",
    "Family": "cephalosporins",
    "Compound": "cefditoren",
    "Formula": "C19H17N6O5S3",
    "Charge": -1,
    "accession": "MD-A007P8",
    "inchikey": "KMIPKYQIOVAHOP-LWJMVPTMSA-N",
    "pubchem": "72543801"
  },
  {
    "FAIR_ID": "ABDB007009",
    "Family": "cephalosporins",
    "Compound": "cefepime",
    "Formula": "C19H24N6O5S2",
    "Charge": 0,
    "accession": "MD-A007P9",
    "inchikey": "HVFLCNVBZFFHBT-CXAGYDPISA-N",
    "pubchem": "68606"
  },
  {
    "FAIR_ID": "ABDB007010",
    "Family": "cephalosporins",
    "Compound": "cefetamet",
    "Formula": "C14H14N5O5S2",
    "Charge": -1,
    "accession": "MD-A007PA",
    "inchikey": "MQLRYUCJDNBWMV-RWFJUVPESA-N",
    "pubchem": "5486821"
  },
  {
    "FAIR_ID": "ABDB007011",
    "Family": "cephalosporins",
    "Compound": "cefiderocol",
    "Formula": "C30H33ClN7O10S2",
    "Charge": -1,
    "accession": "MD-A007PB",
    "inchikey": "DBPPRLRVDVJOCL-FQRUVTKNSA-N",
    "pubchem": "77843966"
  },
  {
    "FAIR_ID": "ABDB007012",
    "Family": "cephalosporins",
    "Compound": "cefixime",
    "Formula": "C16H13N5O7S2",
    "Charge": -2,
    "accession": "MD-A007PC",
    "inchikey": "OKBVVJOGVLARMR-VINNURBNSA-N",
    "pubchem": "6321411"
  },
  {
    "FAIR_ID": "ABDB007013",
    "Family": "cephalosporins",
    "Compound": "cefmenoxime",
    "Formula": "C16H16N9O5S3",
    "Charge": -1,
    "accession": "MD-A007PD",
    "inchikey": "HJJDBAOLQAWBMH-DKQCJYJNSA-N",
    "pubchem": "5361486"
  },
  {
    "FAIR_ID": "ABDB007014",
    "Family": "cephalosporins",
    "Compound": "cefmetazole",
    "Formula": "C15H16N7O5S3",
    "Charge": -1,
    "accession": "MD-A007PE",

<a id="browsing"></a>
## Browsing AB-DB Database

**Browse** the **AB-DB collection** from the **MDDB database**.

In [5]:
from collections import defaultdict

families = defaultdict(list)

compounds_request = f'{api_url}/compounds?limit=1000'

# Query the API
with urllib.request.urlopen(compounds_request) as response:
    parsed_response = json.loads(response.read().decode("utf-8"))

for entry in parsed_response['data']:
    #compound = entry['Compound']
    family = entry['Family'].title()
    families[family].append(entry)

for family, entries in families.items():
    print(f"=== {family} ===")
    for entry in entries:
        print(f"- Compound: {entry['Compound']}, Charge: {entry['Charge']}, ABDB Accession: {entry['FAIR_ID']}")
    print()

=== Aminocoumarins ===

- Compound: chlorobiocin, Charge: -1, ABDB Accession: ABDB001001

- Compound: declovanillobiocin, Charge: -1, ABDB Accession: ABDB001002

- Compound: isovanillobiocin, Charge: -1, ABDB Accession: ABDB001003

- Compound: novclobiocin_101, Charge: -1, ABDB Accession: ABDB001004

- Compound: novobiocin, Charge: -1, ABDB Accession: ABDB001005

- Compound: plazomicin, Charge: 5, ABDB Accession: ABDB001006

- Compound: ribostamycin, Charge: 3, ABDB Accession: ABDB001007

- Compound: ribostamycin, Charge: 4, ABDB Accession: ABDB001008

- Compound: vanillobiocin, Charge: -1, ABDB Accession: ABDB001009

- Compound: coumermycin_A1, Charge: 0, ABDB Accession: ABDB001010

=== Aminoglycosides ===

- Compound: amikacin, Charge: 3, ABDB Accession: ABDB002001

- Compound: amikacin, Charge: 4, ABDB Accession: ABDB002002

- Compound: apramycin, Charge: 4, ABDB Accession: ABDB002003

- Compound: arbekacin, Charge: 4, ABDB Accession: ABDB002004

- Compound: arbekacin, Charge: 5, ABDB Accession: ABDB002005

- Compound: dibekacin, Charge: 4, ABDB Accession: ABDB002006

- Compound: dibekacin, Charge: 5, ABDB Accession: ABDB002007

- Compound: gentamicin, Charge: 4, ABDB Accession: ABDB002008

- Compound: hygrovetine, Charge: 2, ABDB Accession: ABDB002009

- Compound: hygrovetine, Charge: 3, ABDB Accession: ABDB002010

- Compound: isepamicin, Charge: 4, ABDB Accession: ABDB002011

- Compound: kanamycin, Charge: 3, ABDB Accession: ABDB002012

- Compound: kanamycin, Charge: 4, ABDB Accession: ABDB002013

- Compound: neomycin, Charge: 5, ABDB Accession: ABDB002014

- Compound: neomycin, Charge: 6, ABDB Accession: ABDB002015

- Compound: netilmicin, Charge: 4, ABDB Accession: ABDB002016

- Compound: netilmicin, Charge: 5, ABDB Accession: ABDB002017

- Compound: paromomycin, Charge: 4, ABDB Accession: ABDB002018

- Compound: paromomycin, Charge: 5, ABDB Accession: ABDB002019

- Compound: sisomicin, Charge: 4, ABDB Accession: ABDB002020

- Compound: sisomicin, Charge: 5, ABDB Accession: ABDB002021

- Compound: spectinomycin, Charge: 1, ABDB Accession: ABDB002022

- Compound: spectinomycin, Charge: 2, ABDB Accession: ABDB002023

- Compound: streptomycin, Charge: 3, ABDB Accession: ABDB002024

- Compound: tobramycin, Charge: 4, ABDB Accession: ABDB002025

- Compound: tobramycin, Charge: 5, ABDB Accession: ABDB002026

- Compound: astromicin, Charge: 4, ABDB Accession: ABDB002027

- Compound: dihydrostreptomycin, Charge: 3, ABDB Accession: ABDB002028

- Compound: micronomicin, Charge: 4, ABDB Accession: ABDB002029

=== Anthracenediones ===

- Compound: mitoxantrone, Charge: 2, ABDB Accession: ABDB003001

- Compound: pixantrone, Charge: 2, ABDB Accession: ABDB003002

=== Anthracyclines ===

- Compound: daunorubicin, Charge: 1, ABDB Accession: ABDB004001

- Compound: doxorubicin, Charge: 1, ABDB Accession: ABDB004002

- Compound: epirubicin, Charge: 1, ABDB Accession: ABDB004003

- Compound: idarubicin, Charge: 1, ABDB Accession: ABDB004004

=== Beta-Lactamase-Inhibitors ===

- Compound: avibactam, Charge: -1, ABDB Accession: ABDB005001

- Compound: bal29880, Charge: 0, ABDB Accession: ABDB005002

- Compound: clavulanic_acid, Charge: -1, ABDB Accession: ABDB005003

- Compound: durlobactam, Charge: -1, ABDB Accession: ABDB005004

- Compound: enmetazobactam, Charge: 0, ABDB Accession: ABDB005005

- Compound: nacubactam, Charge: 0, ABDB Accession: ABDB005006

- Compound: relebactam, Charge: 0, ABDB Accession: ABDB005007

- Compound: sulbactam, Charge: -1, ABDB Accession: ABDB005008

- Compound: tazobactam, Charge: -1, ABDB Accession: ABDB005009

- Compound: thienamycin, Charge: 0, ABDB Accession: ABDB005010

- Compound: zidebactam, Charge: 0, ABDB Accession: ABDB005011

- Compound: WCK-4234, Charge: -1, ABDB Accession: ABDB005012

- Compound: vaborbactam, Charge: -1, ABDB Accession: ABDB005013

=== Carbapenems ===

- Compound: biapenem, Charge: 0, ABDB Accession: ABDB006001

- Compound: doripenem, Charge: 0, ABDB Accession: ABDB006002

- Compound: ertapenem, Charge: -1, ABDB Accession: ABDB006003

- Compound: faropenem, Charge: -1, ABDB Accession: ABDB006004

- Compound: imipenem, Charge: 0, ABDB Accession: ABDB006005

- Compound: LK-157, Charge: -1, ABDB Accession: ABDB006006

- Compound: meropenem, Charge: 0, ABDB Accession: ABDB006007

- Compound: olivanic_acid, Charge: 0, ABDB Accession: ABDB006008

- Compound: panipenem, Charge: 0, ABDB Accession: ABDB006009

- Compound: razupenem, Charge: 0, ABDB Accession: ABDB006010

- Compound: ritipenem, Charge: -1, ABDB Accession: ABDB006011

- Compound: sanfetrinem, Charge: -1, ABDB Accession: ABDB006012

- Compound: tebipenem, Charge: -1, ABDB Accession: ABDB006013

- Compound: tomopenem, Charge: 1, ABDB Accession: ABDB006014

=== Cephalosporins ===

- Compound: cefaclor, Charge: 0, ABDB Accession: ABDB007001

- Compound: cefadroxil, Charge: 0, ABDB Accession: ABDB007002

- Compound: cefalonium, Charge: 0, ABDB Accession: ABDB007003

- Compound: cefamandole_nafate, Charge: -1, ABDB Accession: ABDB007004

- Compound: cefamandole_sodium, Charge: -1, ABDB Accession: ABDB007005

- Compound: cefazolin, Charge: -1, ABDB Accession: ABDB007006

- Compound: cefdinir, Charge: -2, ABDB Accession: ABDB007007

- Compound: cefditoren, Charge: -1, ABDB Accession: ABDB007008

- Compound: cefepime, Charge: 0, ABDB Accession: ABDB007009

- Compound: cefetamet, Charge: -1, ABDB Accession: ABDB007010

- Compound: cefiderocol, Charge: -1, ABDB Accession: ABDB007011

- Compound: cefixime, Charge: -2, ABDB Accession: ABDB007012

- Compound: cefmenoxime, Charge: -1, ABDB Accession: ABDB007013

- Compound: cefmetazole, Charge: -1, ABDB Accession: ABDB007014

- Compound: cefonicid, Charge: -2, ABDB Accession: ABDB007015

- Compound: cefoperazone, Charge: -1, ABDB Accession: ABDB007016

- Compound: ceforanide, Charge: -1, ABDB Accession: ABDB007017

- Compound: cefotaxime, Charge: -1, ABDB Accession: ABDB007018

- Compound: cefotetan, Charge: -2, ABDB Accession: ABDB007019

- Compound: cefoxitin, Charge: -1, ABDB Accession: ABDB007020

- Compound: cefpiramide, Charge: -1, ABDB Accession: ABDB007021

- Compound: cefpirome, Charge: 0, ABDB Accession: ABDB007022

- Compound: cefpodoxime, Charge: -1, ABDB Accession: ABDB007023

- Compound: cefprozil, Charge: 0, ABDB Accession: ABDB007024

- Compound: cefsulodin, Charge: -1, ABDB Accession: ABDB007025

- Compound: ceftaroline, Charge: 0, ABDB Accession: ABDB007026

- Compound: ceftazidime, Charge: -1, ABDB Accession: ABDB007027

- Compound: ceftibuten, Charge: -2, ABDB Accession: ABDB007028

- Compound: ceftizoxime, Charge: -1, ABDB Accession: ABDB007029

- Compound: ceftobiprole, Charge: 0, ABDB Accession: ABDB007030

- Compound: ceftriaxone, Charge: -1, ABDB Accession: ABDB007031

- Compound: cefuroxime, Charge: -1, ABDB Accession: ABDB007032

- Compound: cephalexin, Charge: 0, ABDB Accession: ABDB007033

- Compound: cephaloridine, Charge: 0, ABDB Accession: ABDB007034

- Compound: cephalotin, Charge: -1, ABDB Accession: ABDB007035

- Compound: cephapirin, Charge: -1, ABDB Accession: ABDB007036

- Compound: cephradine, Charge: 0, ABDB Accession: ABDB007037

- Compound: loracarbef, Charge: 0, ABDB Accession: ABDB007038

- Compound: loracarbef, Charge: -1, ABDB Accession: ABDB007039

- Compound: nitrocefin, Charge: -1, ABDB Accession: ABDB007040

- Compound: cefacetrile, Charge: -1, ABDB Accession: ABDB007041

- Compound: cefatrizine, Charge: 0, ABDB Accession: ABDB007042

- Compound: cefazedone, Charge: -1, ABDB Accession: ABDB007043

- Compound: cefbuperazone, Charge: -1, ABDB Accession: ABDB007044

- Compound: cefcapene, Charge: -1, ABDB Accession: ABDB007045

- Compound: cefminox, Charge: -1, ABDB Accession: ABDB007046

- Compound: cefodizime, Charge: -2, ABDB Accession: ABDB007047

- Compound: cefoselis, Charge: 0, ABDB Accession: ABDB007048

- Compound: cefotiam, Charge: 0, ABDB Accession: ABDB007049

- Compound: cefovecin, Charge: -1, ABDB Accession: ABDB007050

- Compound: cefozopran, Charge: 0, ABDB Accession: ABDB007051

- Compound: cefquinome, Charge: 0, ABDB Accession: ABDB007052

- Compound: cefroxadine, Charge: 0, ABDB Accession: ABDB007053

- Compound: cefteram_pivoxil, Charge: 0, ABDB Accession: ABDB007054

- Compound: ceftezole, Charge: -1, ABDB Accession: ABDB007055

- Compound: ceftiofur, Charge: -1, ABDB Accession: ABDB007056

- Compound: ceftolozane, Charge: 0, ABDB Accession: ABDB007057

- Compound: cephalosporin_C, Charge: -2, ABDB Accession: ABDB007058

- Compound: moxalactam, Charge: -2, ABDB Accession: ABDB007059

=== Dhfr-Inhibitors ===

- Compound: brodimoprim, Charge: 0, ABDB Accession: ABDB008001

- Compound: brodimoprim, Charge: 1, ABDB Accession: ABDB008002

- Compound: epiroprim, Charge: 0, ABDB Accession: ABDB008003

- Compound: iclaprim-R, Charge: 0, ABDB Accession: ABDB008004

- Compound: iclaprim-S, Charge: 0, ABDB Accession: ABDB008005

- Compound: tetroxoprim, Charge: 0, ABDB Accession: ABDB008006

- Compound: tetroxoprim, Charge: 1, ABDB Accession: ABDB008007

- Compound: triclosan, Charge: 0, ABDB Accession: ABDB008008

- Compound: trimethoprim, Charge: 0, ABDB Accession: ABDB008009

- Compound: trimethoprim, Charge: 1, ABDB Accession: ABDB008010

- Compound: ormetoprim, Charge: 0, ABDB Accession: ABDB008011

- Compound: phtalylsulfathiazole, Charge: -1, ABDB Accession: ABDB008012

- Compound: pyrimethamine, Charge: 0, ABDB Accession: ABDB008013

=== Efflux-Pumps-Inhibitors ===

- Compound: amitriptyline, Charge: 1, ABDB Accession: ABDB009001

- Compound: chlorpromazine, Charge: 1, ABDB Accession: ABDB009002

- Compound: D13-9001, Charge: -1, ABDB Accession: ABDB009003

- Compound: MBX2319, Charge: 0, ABDB Accession: ABDB009004

- Compound: MBX2931, Charge: 0, ABDB Accession: ABDB009005

- Compound: MBX2931, Charge: 1, ABDB Accession: ABDB009006

- Compound: MBX3132, Charge: 0, ABDB Accession: ABDB009007

- Compound: MBX3135, Charge: 0, ABDB Accession: ABDB009008

- Compound: NMP, Charge: 1, ABDB Accession: ABDB009009

- Compound: PAbN, Charge: 2, ABDB Accession: ABDB009010

=== Fusidanes ===

- Compound: fusidic_acid, Charge: -1, ABDB Accession: ABDB010001

- Compound: helvolic_acid, Charge: -1, ABDB Accession: ABDB010002

=== Lincosamides ===

- Compound: clindamycin, Charge: 1, ABDB Accession: ABDB011001

- Compound: desalicetin, Charge: 0, ABDB Accession: ABDB011002

- Compound: desalicetin, Charge: 1, ABDB Accession: ABDB011003

- Compound: lincomycin, Charge: 1, ABDB Accession: ABDB011004

- Compound: pirlimycin, Charge: 1, ABDB Accession: ABDB011005

=== Macrolides ===

- Compound: azithromycin, Charge: 2, ABDB Accession: ABDB012001

- Compound: cethromycin, Charge: 1, ABDB Accession: ABDB012002

- Compound: clarithromycin, Charge: 1, ABDB Accession: ABDB012003

- Compound: dirithromycin, Charge: 2, ABDB Accession: ABDB012004

- Compound: erythromycin, Charge: 1, ABDB Accession: ABDB012005

- Compound: modithromycin, Charge: 1, ABDB Accession: ABDB012006

- Compound: roxithromycin, Charge: 1, ABDB Accession: ABDB012007

- Compound: spiramycin, Charge: 2, ABDB Accession: ABDB012008

- Compound: telithromycin, Charge: 1, ABDB Accession: ABDB012009

- Compound: descladinose_azithromycin, Charge: 2, ABDB Accession: ABDB012010

- Compound: fidaxomicin, Charge: 0, ABDB Accession: ABDB012011

- Compound: flurithromycin, Charge: 1, ABDB Accession: ABDB012012

- Compound: gamithromycin, Charge: 2, ABDB Accession: ABDB012013

- Compound: josamycin, Charge: 1, ABDB Accession: ABDB012014

- Compound: kitasamycin, Charge: 1, ABDB Accession: ABDB012015

- Compound: midecamycin, Charge: 1, ABDB Accession: ABDB012016

- Compound: miocamycin, Charge: 1, ABDB Accession: ABDB012017

- Compound: oleandomycin, Charge: 1, ABDB Accession: ABDB012018

- Compound: rokitamycin, Charge: 1, ABDB Accession: ABDB012019

- Compound: solithromycin, Charge: 1, ABDB Accession: ABDB012020

- Compound: tildipirosin, Charge: 3, ABDB Accession: ABDB012021

- Compound: tilmicosin, Charge: 2, ABDB Accession: ABDB012022

- Compound: troleandomycin, Charge: 1, ABDB Accession: ABDB012023

- Compound: tulathromycin, Charge: 3, ABDB Accession: ABDB012024

- Compound: tylosin, Charge: 1, ABDB Accession: ABDB012025

- Compound: tylvalosin, Charge: 1, ABDB Accession: ABDB012026

=== Monobactams ===

- Compound: aztreonam, Charge: -2, ABDB Accession: ABDB013001

- Compound: bal19764, Charge: -1, ABDB Accession: ABDB013002

- Compound: bal30072, Charge: -1, ABDB Accession: ABDB013003

- Compound: carumonam, Charge: -2, ABDB Accession: ABDB013004

- Compound: gloximonam, Charge: 0, ABDB Accession: ABDB013005

- Compound: nacubactam, Charge: -1, ABDB Accession: ABDB013006

- Compound: nocardicin, Charge: -2, ABDB Accession: ABDB013007

- Compound: oximonam, Charge: -1, ABDB Accession: ABDB013008

- Compound: pirazmonam, Charge: -2, ABDB Accession: ABDB013009

- Compound: tigemonam, Charge: -2, ABDB Accession: ABDB013010

=== Nitrofurans ===

- Compound: furazolidone, Charge: 0, ABDB Accession: ABDB014001

- Compound: nifuratel, Charge: 0, ABDB Accession: ABDB014002

- Compound: nifurfoline, Charge: 0, ABDB Accession: ABDB014003

- Compound: nifuroxazide, Charge: 0, ABDB Accession: ABDB014004

- Compound: nifurquinazol, Charge: 0, ABDB Accession: ABDB014005

- Compound: nifurtimox, Charge: 0, ABDB Accession: ABDB014006

- Compound: nifurtoinol, Charge: 0, ABDB Accession: ABDB014007

- Compound: nifurzide, Charge: 0, ABDB Accession: ABDB014008

- Compound: nitrofurantoin, Charge: 0, ABDB Accession: ABDB014009

- Compound: nitrofurazone, Charge: 0, ABDB Accession: ABDB014010

- Compound: nitrovin, Charge: 0, ABDB Accession: ABDB014011

- Compound: tinidazole, Charge: 0, ABDB Accession: ABDB014012

- Compound: furaltadone, Charge: 1, ABDB Accession: ABDB014013

- Compound: furazidine, Charge: 0, ABDB Accession: ABDB014014

=== Nucleosides ===

- Compound: A-500359A, Charge: 0, ABDB Accession: ABDB015001

- Compound: A-503083E, Charge: 0, ABDB Accession: ABDB015002

- Compound: capuramycin, Charge: 0, ABDB Accession: ABDB015003

- Compound: puromycin, Charge: 1, ABDB Accession: ABDB015004

=== Dyes ===

- Compound: acriflavine, Charge: 1, ABDB Accession: ABDB016001

- Compound: HT33342, Charge: 1, ABDB Accession: ABDB016002

- Compound: propidium, Charge: 2, ABDB Accession: ABDB016003

- Compound: rhodamine-6G, Charge: 1, ABDB Accession: ABDB016004

- Compound: proflavine, Charge: 0, ABDB Accession: ABDB016005

=== Anti-Tuberculosis ===

- Compound: cycloserine, Charge: 0, ABDB Accession: ABDB017001

- Compound: ethionamide, Charge: 0, ABDB Accession: ABDB017002

- Compound: isoniazid, Charge: 0, ABDB Accession: ABDB017003

- Compound: bedaquiline, Charge: 1, ABDB Accession: ABDB017004

- Compound: capreomycin, Charge: 4, ABDB Accession: ABDB017005

- Compound: delamanid, Charge: 0, ABDB Accession: ABDB017006

- Compound: morinamide, Charge: 0, ABDB Accession: ABDB017007

- Compound: para-aminosalicylic_acid, Charge: -1, ABDB Accession: ABDB017008

- Compound: pretomanid, Charge: 0, ABDB Accession: ABDB017009

- Compound: protionamide, Charge: 0, ABDB Accession: ABDB017010

- Compound: pyrazinamide, Charge: 0, ABDB Accession: ABDB017011

- Compound: terizidone, Charge: -2, ABDB Accession: ABDB017012

- Compound: tiocarlide, Charge: 0, ABDB Accession: ABDB017013

=== Sulfones ===

- Compound: dapsone, Charge: 0, ABDB Accession: ABDB018001

=== Detergents ===

- Compound: deoxycholate, Charge: -1, ABDB Accession: ABDB019001

- Compound: dodecyl_sulfate, Charge: -1, ABDB Accession: ABDB019002

=== Siderophores ===

- Compound: enterobactin, Charge: -3, ABDB Accession: ABDB020001

=== Bacteriostatics ===

- Compound: ethambutol, Charge: 1, ABDB Accession: ABDB021001

=== Intercalating_Agents ===

- Compound: ethidium, Charge: 1, ABDB Accession: ABDB022001

=== Phosphonics ===

- Compound: fosfomycin, Charge: -1, ABDB Accession: ABDB023001

=== Thiadiazoles ===

- Compound: halicin, Charge: 0, ABDB Accession: ABDB024001

=== Nitroimidazole ===

- Compound: metronidazole, Charge: 0, ABDB Accession: ABDB025001

- Compound: ornidazole, Charge: 0, ABDB Accession: ABDB025002

- Compound: ronidazole, Charge: 0, ABDB Accession: ABDB025003

- Compound: secnidazole, Charge: 0, ABDB Accession: ABDB025004

=== Fatty_Acid_Synthases_Inhibitors ===

- Compound: platensimycin, Charge: -1, ABDB Accession: ABDB026001

=== Pseudomonic_Acids ===

- Compound: pseudomonic_acid_A, Charge: -1, ABDB Accession: ABDB027001

- Compound: pseudomonic_acid_B, Charge: -1, ABDB Accession: ABDB027002

=== Bile_Salts ===

- Compound: taurocholate, Charge: -1, ABDB Accession: ABDB028001

=== Cationic_Agents ===

- Compound: tetraphenylphosphonium, Charge: 1, ABDB Accession: ABDB029001

=== Oxacephem ===

- Compound: flomoxef, Charge: -1, ABDB Accession: ABDB030001

- Compound: latamoxef, Charge: -2, ABDB Accession: ABDB030002

=== Oxazolidinones ===

- Compound: contezolid, Charge: 0, ABDB Accession: ABDB031001

- Compound: eperezolid, Charge: 0, ABDB Accession: ABDB031002

- Compound: linezolid, Charge: 0, ABDB Accession: ABDB031003

- Compound: posizolid, Charge: 0, ABDB Accession: ABDB031004

- Compound: radezolid, Charge: 1, ABDB Accession: ABDB031005

- Compound: ranbezolid, Charge: 0, ABDB Accession: ABDB031006

- Compound: sutezolid, Charge: 0, ABDB Accession: ABDB031007

- Compound: tedizolid, Charge: 0, ABDB Accession: ABDB031008

- Compound: cadazolid, Charge: -1, ABDB Accession: ABDB031009

=== Penicillins ===

- Compound: 6apa, Charge: -1, ABDB Accession: ABDB032001

- Compound: amoxicillin, Charge: 0, ABDB Accession: ABDB032002

- Compound: ampicillin, Charge: 0, ABDB Accession: ABDB032003

- Compound: azlocillin, Charge: -1, ABDB Accession: ABDB032004

- Compound: carbenicillin, Charge: -2, ABDB Accession: ABDB032005

- Compound: cloxacillin, Charge: -1, ABDB Accession: ABDB032006

- Compound: dicloxacillin, Charge: -1, ABDB Accession: ABDB032007

- Compound: epicillin, Charge: 0, ABDB Accession: ABDB032008

- Compound: flucloxacillin, Charge: -1, ABDB Accession: ABDB032009

- Compound: hetacillin, Charge: -1, ABDB Accession: ABDB032010

- Compound: methicillin, Charge: -1, ABDB Accession: ABDB032011

- Compound: mezlocillin, Charge: -1, ABDB Accession: ABDB032012

- Compound: nafcillin, Charge: -1, ABDB Accession: ABDB032013

- Compound: oxacillin, Charge: -1, ABDB Accession: ABDB032014

- Compound: penicillinG, Charge: -1, ABDB Accession: ABDB032015

- Compound: penicillinV, Charge: -1, ABDB Accession: ABDB032016

- Compound: piperacillin, Charge: -1, ABDB Accession: ABDB032017

- Compound: sulbenicillin, Charge: -2, ABDB Accession: ABDB032018

- Compound: temocillin, Charge: -2, ABDB Accession: ABDB032019

- Compound: ticarcillin, Charge: -2, ABDB Accession: ABDB032020

- Compound: azidocillin, Charge: -1, ABDB Accession: ABDB032021

- Compound: bacampicillin, Charge: 1, ABDB Accession: ABDB032022

- Compound: carindacillin, Charge: -1, ABDB Accession: ABDB032023

- Compound: clometocillin, Charge: -1, ABDB Accession: ABDB032024

- Compound: mecillinam, Charge: 0, ABDB Accession: ABDB032025

- Compound: metampicillin, Charge: -1, ABDB Accession: ABDB032026

- Compound: penamecillin, Charge: 0, ABDB Accession: ABDB032027

- Compound: penethamate_hydriodide, Charge: 1, ABDB Accession: ABDB032028

- Compound: pheneticillin, Charge: -1, ABDB Accession: ABDB032029

- Compound: pivampicillin, Charge: 0, ABDB Accession: ABDB032030

- Compound: pivmecillinam, Charge: 1, ABDB Accession: ABDB032031

- Compound: propicillin, Charge: -1, ABDB Accession: ABDB032032

- Compound: sultamicillin, Charge: 0, ABDB Accession: ABDB032033

- Compound: talampicillin, Charge: 0, ABDB Accession: ABDB032034

=== Phenicols ===

- Compound: azidamfenicol, Charge: 0, ABDB Accession: ABDB033001

- Compound: chloramphenicol, Charge: 0, ABDB Accession: ABDB033002

- Compound: florfenicol, Charge: 0, ABDB Accession: ABDB033003

- Compound: tevenel, Charge: 0, ABDB Accession: ABDB033004

- Compound: thiamphenicol, Charge: 0, ABDB Accession: ABDB033005

=== Quinolones ===

- Compound: cinoxacin, Charge: -1, ABDB Accession: ABDB034001

- Compound: ciprofloxacin, Charge: 0, ABDB Accession: ABDB034002

- Compound: ciprofloxacin, Charge: -1, ABDB Accession: ABDB034003

- Compound: clinafloxacin, Charge: 0, ABDB Accession: ABDB034004

- Compound: danofloxacin, Charge: 0, ABDB Accession: ABDB034005

- Compound: delafloxacin, Charge: -1, ABDB Accession: ABDB034006

- Compound: difloxacin, Charge: 0, ABDB Accession: ABDB034007

- Compound: difloxacin, Charge: -1, ABDB Accession: ABDB034008

- Compound: dx-619, Charge: 0, ABDB Accession: ABDB034009

- Compound: enoxacin, Charge: 0, ABDB Accession: ABDB034010

- Compound: enoxacin, Charge: -1, ABDB Accession: ABDB034011

- Compound: enrofloxacin, Charge: 0, ABDB Accession: ABDB034012

- Compound: enrofloxacin, Charge: -1, ABDB Accession: ABDB034013

- Compound: fleroxacin, Charge: 0, ABDB Accession: ABDB034014

- Compound: fleroxacin, Charge: -1, ABDB Accession: ABDB034015

- Compound: flumequine, Charge: -1, ABDB Accession: ABDB034016

- Compound: garenoxacin, Charge: 0, ABDB Accession: ABDB034017

- Compound: gatifloxacin, Charge: 0, ABDB Accession: ABDB034018

- Compound: gemifloxacin, Charge: 0, ABDB Accession: ABDB034019

- Compound: grepafloxacin, Charge: 0, ABDB Accession: ABDB034020

- Compound: levofloxacin, Charge: 0, ABDB Accession: ABDB034021

- Compound: levofloxacin, Charge: -1, ABDB Accession: ABDB034022

- Compound: lomefloxacin, Charge: 0, ABDB Accession: ABDB034023

- Compound: lomefloxacin, Charge: -1, ABDB Accession: ABDB034024

- Compound: marbofloxacin, Charge: -1, ABDB Accession: ABDB034025

- Compound: moxifloxacin, Charge: 0, ABDB Accession: ABDB034026

- Compound: nadifloxacin, Charge: -1, ABDB Accession: ABDB034027

- Compound: nalidixic_acid, Charge: -1, ABDB Accession: ABDB034028

- Compound: norfloxacin, Charge: 0, ABDB Accession: ABDB034029

- Compound: norfloxacin, Charge: -1, ABDB Accession: ABDB034030

- Compound: ofloxacin, Charge: 0, ABDB Accession: ABDB034031

- Compound: ofloxacin, Charge: -1, ABDB Accession: ABDB034032

- Compound: orbifloxacin, Charge: 0, ABDB Accession: ABDB034033

- Compound: oxolinic_acid, Charge: -1, ABDB Accession: ABDB034034

- Compound: pazufloxacin, Charge: 0, ABDB Accession: ABDB034035

- Compound: pefloxacin, Charge: 0, ABDB Accession: ABDB034036

- Compound: pefloxacin, Charge: -1, ABDB Accession: ABDB034037

- Compound: pipemidic_acid, Charge: 0, ABDB Accession: ABDB034038

- Compound: prulifloxacin, Charge: -1, ABDB Accession: ABDB034039

- Compound: rosoxacin, Charge: -1, ABDB Accession: ABDB034040

- Compound: rufloxacin, Charge: 0, ABDB Accession: ABDB034041

- Compound: sarafloxacin, Charge: 0, ABDB Accession: ABDB034042

- Compound: sarafloxacin, Charge: -1, ABDB Accession: ABDB034043

- Compound: sitafloxacin, Charge: 0, ABDB Accession: ABDB034044

- Compound: sparfloxacin, Charge: 0, ABDB Accession: ABDB034045

- Compound: temafloxacin, Charge: 0, ABDB Accession: ABDB034046

- Compound: trovafloxacin, Charge: 0, ABDB Accession: ABDB034047

- Compound: avarofloxacin, Charge: 0, ABDB Accession: ABDB034048

- Compound: besifloxacin, Charge: 0, ABDB Accession: ABDB034049

- Compound: finafloxacin, Charge: 0, ABDB Accession: ABDB034050

- Compound: halquinol, Charge: 0, ABDB Accession: ABDB034051

- Compound: ibafloxacin, Charge: -1, ABDB Accession: ABDB034052

- Compound: lascufloxacin, Charge: 0, ABDB Accession: ABDB034053

- Compound: levonadifloxacin, Charge: -1, ABDB Accession: ABDB034054

- Compound: nemonoxacin, Charge: 0, ABDB Accession: ABDB034055

- Compound: ozenoxacin, Charge: -1, ABDB Accession: ABDB034056

- Compound: piromidic_acid, Charge: -1, ABDB Accession: ABDB034057

- Compound: pradofloxacin, Charge: 0, ABDB Accession: ABDB034058

- Compound: zabofloxacin, Charge: 0, ABDB Accession: ABDB034059

=== Rifamycins ===

- Compound: rifalazil, Charge: 0, ABDB Accession: ABDB035001

- Compound: rifampicin, Charge: 0, ABDB Accession: ABDB035002

- Compound: rifampicin, Charge: 1, ABDB Accession: ABDB035003

- Compound: rifabutin, Charge: 1, ABDB Accession: ABDB035004

- Compound: rifamycin, Charge: 0, ABDB Accession: ABDB035005

- Compound: rifapentine, Charge: 1, ABDB Accession: ABDB035006

- Compound: rifaximin, Charge: 0, ABDB Accession: ABDB035007

=== Streptogramins ===

- Compound: dalfopristin, Charge: 0, ABDB Accession: ABDB036001

- Compound: pristinamycin, Charge: 0, ABDB Accession: ABDB036002

- Compound: quinupristin, Charge: 1, ABDB Accession: ABDB036003

- Compound: virginiamycin, Charge: 0, ABDB Accession: ABDB036004

=== Sulphonamides ===

- Compound: sulfabenzamide, Charge: -1, ABDB Accession: ABDB037001

- Compound: sulfacetamide, Charge: -1, ABDB Accession: ABDB037002

- Compound: sulfachlorpyridazine, Charge: -1, ABDB Accession: ABDB037003

- Compound: sulfadiazine, Charge: -1, ABDB Accession: ABDB037004

- Compound: sulfadimethoxine, Charge: -1, ABDB Accession: ABDB037005

- Compound: sulfaguanidine, Charge: 0, ABDB Accession: ABDB037006

- Compound: sulfamerazine, Charge: 0, ABDB Accession: ABDB037007

- Compound: sulfamerazine, Charge: -1, ABDB Accession: ABDB037008

- Compound: sulfameter, Charge: -1, ABDB Accession: ABDB037009

- Compound: sulfamethazine, Charge: 0, ABDB Accession: ABDB037010

- Compound: sulfamethazine, Charge: -1, ABDB Accession: ABDB037011

- Compound: sulfamethizole, Charge: -1, ABDB Accession: ABDB037012

- Compound: sulfamethoxazole, Charge: -1, ABDB Accession: ABDB037013

- Compound: sulfamethoxypyridazine, Charge: -1, ABDB Accession: ABDB037014

- Compound: sulfamonomethoxine, Charge: -1, ABDB Accession: ABDB037015

- Compound: sulfamylon, Charge: 1, ABDB Accession: ABDB037016

- Compound: sulfanitran, Charge: 0, ABDB Accession: ABDB037017

- Compound: sulfanitran, Charge: -1, ABDB Accession: ABDB037018

- Compound: sulfaphenazole, Charge: -1, ABDB Accession: ABDB037019

- Compound: sulfapyridine, Charge: -1, ABDB Accession: ABDB037020

- Compound: sulfaquinoxaline, Charge: -1, ABDB Accession: ABDB037021

- Compound: sulfathiazole, Charge: 0, ABDB Accession: ABDB037022

- Compound: sulfathiazole, Charge: -1, ABDB Accession: ABDB037023

- Compound: sulfisoxazole, Charge: -1, ABDB Accession: ABDB037024

- Compound: phthalylsulfacetamide, Charge: -2, ABDB Accession: ABDB037025

- Compound: sulfacarbamide, Charge: -1, ABDB Accession: ABDB037026

- Compound: sulfadoxine, Charge: -1, ABDB Accession: ABDB037027

- Compound: sulfaisodimidine, Charge: -1, ABDB Accession: ABDB037028

- Compound: sulfalene, Charge: -1, ABDB Accession: ABDB037029

- Compound: sulfamazone, Charge: -2, ABDB Accession: ABDB037030

- Compound: sulfametomidine, Charge: -1, ABDB Accession: ABDB037031

- Compound: sulfametrole, Charge: -1, ABDB Accession: ABDB037032

- Compound: sulfamoxole, Charge: -1, ABDB Accession: ABDB037033

- Compound: sulfanilamide, Charge: 0, ABDB Accession: ABDB037034

- Compound: sulfaperin, Charge: -1, ABDB Accession: ABDB037035

- Compound: sulfathiourea, Charge: -1, ABDB Accession: ABDB037036

- Compound: sulfisoxazole_acetyl, Charge: 0, ABDB Accession: ABDB037037

=== Tetracyclines ===

- Compound: chlortetracycline, Charge: 0, ABDB Accession: ABDB038001

- Compound: demeclocycline, Charge: 0, ABDB Accession: ABDB038002

- Compound: doxycycline, Charge: 0, ABDB Accession: ABDB038003

- Compound: meclocycline, Charge: 0, ABDB Accession: ABDB038004

- Compound: methacycline, Charge: 0, ABDB Accession: ABDB038005

- Compound: minocycline, Charge: 0, ABDB Accession: ABDB038006

- Compound: omadacycline, Charge: 1, ABDB Accession: ABDB038007

- Compound: oxytetracycline, Charge: 0, ABDB Accession: ABDB038008

- Compound: tetracycline, Charge: 0, ABDB Accession: ABDB038009

- Compound: tigecycline, Charge: 1, ABDB Accession: ABDB038010

- Compound: clomocycline, Charge: 0, ABDB Accession: ABDB038011

- Compound: eravacycline, Charge: 1, ABDB Accession: ABDB038012

- Compound: lymecycline, Charge: 1, ABDB Accession: ABDB038013

- Compound: pipacycline, Charge: 1, ABDB Accession: ABDB038014

- Compound: rolitetracycline, Charge: 1, ABDB Accession: ABDB038015

- Compound: sarecycline, Charge: 0, ABDB Accession: ABDB038016

=== Lipo-Glyco-Peptides ===

- Compound: A47934, Charge: -1, ABDB Accession: ABDB039001

- Compound: bahlimycin, Charge: 1, ABDB Accession: ABDB039002

- Compound: chloroeremomycin, Charge: 2, ABDB Accession: ABDB039003

- Compound: dalbavancin, Charge: 1, ABDB Accession: ABDB039004

- Compound: daptomycin, Charge: -3, ABDB Accession: ABDB039005

- Compound: gausemycin A, Charge: -1, ABDB Accession: ABDB039006

- Compound: oritavancin, Charge: 2, ABDB Accession: ABDB039007

- Compound: ramoplanin_A1, Charge: 2, ABDB Accession: ABDB039008

- Compound: ramoplanin_A2, Charge: 2, ABDB Accession: ABDB039009

- Compound: ramoplanin_A3, Charge: 2, ABDB Accession: ABDB039010

- Compound: teicoplanin, Charge: 0, ABDB Accession: ABDB039011

- Compound: telavancin, Charge: 1, ABDB Accession: ABDB039012

- Compound: vancomycin, Charge: 1, ABDB Accession: ABDB039013

=== Orthosomycins ===

- Compound: avilamycin, Charge: 0, ABDB Accession: ABDB040001

=== Pleuromutilins ===

- Compound: azamulin, Charge: 0, ABDB Accession: ABDB041001

- Compound: BC-3205, Charge: 1, ABDB Accession: ABDB041002

- Compound: BC-7013, Charge: 0, ABDB Accession: ABDB041003

- Compound: lefamulin, Charge: 1, ABDB Accession: ABDB041004

- Compound: pleuromutilin, Charge: 0, ABDB Accession: ABDB041005

- Compound: retapamulin, Charge: 1, ABDB Accession: ABDB041006

- Compound: tiamulin, Charge: 1, ABDB Accession: ABDB041007

- Compound: valnemulin, Charge: 1, ABDB Accession: ABDB041008

=== Cyclic-Polypeptides ===

- Compound: bacitracin, Charge: 0, ABDB Accession: ABDB042001

- Compound: enramycin_A, Charge: 2, ABDB Accession: ABDB042002

- Compound: enramycin_B, Charge: 2, ABDB Accession: ABDB042003

=== Bicyclomycins ===

- Compound: bicozamycin, Charge: 0, ABDB Accession: ABDB043001

=== Ionophores ===

- Compound: calcimycin, Charge: -1, ABDB Accession: ABDB044001

- Compound: ionomycin, Charge: -1, ABDB Accession: ABDB044002

- Compound: laidlomycin, Charge: -1, ABDB Accession: ABDB044003

- Compound: lasalocid, Charge: -1, ABDB Accession: ABDB044004

- Compound: maduramicin, Charge: -1, ABDB Accession: ABDB044005

- Compound: monensin, Charge: -1, ABDB Accession: ABDB044006

- Compound: nanchangmycin, Charge: -1, ABDB Accession: ABDB044007

- Compound: narasin, Charge: -1, ABDB Accession: ABDB044008

- Compound: salinomycin, Charge: -1, ABDB Accession: ABDB044009

- Compound: semduramicin, Charge: -1, ABDB Accession: ABDB044010

- Compound: tetronasin, Charge: 0, ABDB Accession: ABDB044011

=== Quinoxalines ===

- Compound: carbadox, Charge: 0, ABDB Accession: ABDB045001

- Compound: olaquindox, Charge: 0, ABDB Accession: ABDB045002

=== Riminofenazines ===

- Compound: clofazimine, Charge: 0, ABDB Accession: ABDB046001

- Compound: TBI-166, Charge: 0, ABDB Accession: ABDB046002

=== Phenols ===

- Compound: clofoctol, Charge: 0, ABDB Accession: ABDB047001

- Compound: triclosan, Charge: 0, ABDB Accession: ABDB047002

=== Polymyxin ===

- Compound: colistin, Charge: 5, ABDB Accession: ABDB048001

- Compound: polymyxin B, Charge: 5, ABDB Accession: ABDB048002

- Compound: soralimixin, Charge: 5, ABDB Accession: ABDB048003

- Compound: SPR-206, Charge: 5, ABDB Accession: ABDB048004

- Compound: SPR-741, Charge: 3, ABDB Accession: ABDB048005

=== Phospho-Glyco-Lipids ===

- Compound: flavomycin, Charge: -3, ABDB Accession: ABDB049001

- Compound: moenomycin, Charge: -2, ABDB Accession: ABDB049002

=== Arsenicals ===

- Compound: nitarsone, Charge: 0, ABDB Accession: ABDB050001

- Compound: roxarsone, Charge: 0, ABDB Accession: ABDB050002

=== Quinolines ===

- Compound: nitroxoline, Charge: 0, ABDB Accession: ABDB051001

In [6]:
import ipywidgets as widgets
from IPython.display import display, Markdown

# Dropdown
dropdown = widgets.Dropdown(
    options=sorted(families.keys()),
    description="Family:",
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='300px')
)
output = widgets.Output()

def show_class(change):
    output.clear_output()
    clase = change['new']
    with output:
        print(f"=== {clase} ===\n")
        for entry in families[clase]:
            print(f"--- {entry['FAIR_ID']} ---")
            print(f"{entry['Compound'].title()} {entry['Charge']}, {entry['Formula']}")
            print(f"{web_url}/compounds/{entry['FAIR_ID']}\n")

dropdown.observe(show_class, names='value')

display(dropdown, output)

Dropdown(description='Family:', layout=Layout(width='300px'), options=('Aminocoumarins', 'Aminoglycosides', 'A…

Output()

<a id="searching"></a>
## Searching & Finding in the AB-DB Database

**Searching** for a particular entry from the **AB-DB collection**.

In [7]:
# Keyword to search for:
keyword = "aminocoumarins"

# Get a list with all compounds from the specified family from the AB-DB collection
simulations_request = api_url + f'/compounds?family={keyword}'

# Query the API
with urllib.request.urlopen(simulations_request) as response:
    parsed_response = json.loads(response.read().decode("utf-8"))

#print(json.dumps(parsed_response['data'], indent=2))

for entry in parsed_response['data']:
    compound = entry['Compound']
    family = entry['Family']
    charge = entry['Charge']
    print(f"{family.title()}-{compound.title()} (Charge: {charge})")
    print(f"{web_url}/compounds/{entry['FAIR_ID']}\n")

Aminocoumarins-Chlorobiocin (Charge: -1)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001001

Aminocoumarins-Declovanillobiocin (Charge: -1)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001002

Aminocoumarins-Isovanillobiocin (Charge: -1)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001003

Aminocoumarins-Novclobiocin_101 (Charge: -1)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001004

Aminocoumarins-Novobiocin (Charge: -1)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001005

Aminocoumarins-Plazomicin (Charge: 5)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001006

Aminocoumarins-Ribostamycin (Charge: 3)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001007

Aminocoumarins-Ribostamycin (Charge: 4)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001008

Aminocoumarins-Vanillobiocin (Charge: -1)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001009

Aminocoumarins-Coumermycin_A1 (Charge: 0)

https://mmb.irbbarcelona.org/ABDB/compounds/ABDB001010

<a id="descriptors"></a>
## Physico-chemical Descriptors from AB-DB

In [8]:
# Accession to search for:
accession = "ABDB001006"

# Set the descriptors query URL for the API
specific_project_url = api_url + f'/compounds/{accession}'
descriptors_query = specific_project_url + '/files/csv'
print('We query the API at ' + descriptors_query)

# Download the file with an arbitrary name
descriptors_filename = f'{accession}_descriptors.csv'

# Query the API
urllib.request.urlretrieve(descriptors_query, descriptors_filename)

if exists(descriptors_filename):
    print(f'File has been downloaded successfully ({descriptors_filename})')

df = pd.read_csv(descriptors_filename)
df.style.set_table_attributes('class="dataframe table table-striped table-bordered"')

We query the API at https://mmb.irbbarcelona.org/ABDB/api/compounds/ABDB001006/files/csv

File has been downloaded successfully (ABDB001006_descriptors.csv)

<a id="md"></a>
## MD Data from AB-DB

**Downloading** and **visualizing** **MD data** for a particular **AB-DB compound**.

1) **Structure downloading**
2) **Structure visualization**
3) **Trajectory downloading**
4) **Trajectory visualization**
5) **Trajectory analyses (MDDB)**

***
1) **Structure downloading**
***

In [9]:
# Set the structure query URL for the API
specific_project_url = api_url + f'/compounds/{accession}'
structure_query = specific_project_url + '/files/structure.pdb'
print('We query the API at ' + structure_query)

# Download the file with an arbitrary name
structure_filename = f'{accession}_structure.pdb'

# Query the API
urllib.request.urlretrieve(structure_query, structure_filename)

if exists(structure_filename):
    print(f'File has been downloaded successfully ({structure_filename})')

We query the API at https://mmb.irbbarcelona.org/ABDB/api/compounds/ABDB001006/files/structure.pdb

File has been downloaded successfully (ABDB001006_structure.pdb)

***
2) **Structure visualization**
***

In [10]:
view = nglview.show_structure_file(structure_filename)
view._remote_call('setSize', target='Widget', args=['','600px'])
view

NGLWidget()

***
3) **Trajectory downloading**
***

In [11]:
# Set the trajectory query URL for the API
specific_project_url = api_url + f'/compounds/{accession}'
trajectory_query = specific_project_url + '/files/trajectory.xtc'
print('We query the API at ' + trajectory_query)

# Download the file with an arbitrary name
trajectory_filename = f'{accession}_trajectory.xtc'

# Query the API
urllib.request.urlretrieve(trajectory_query, trajectory_filename)

if exists(trajectory_filename):
    print(f'File has been downloaded successfully ({trajectory_filename})')

We query the API at https://mmb.irbbarcelona.org/ABDB/api/compounds/ABDB001006/files/trajectory.xtc

File has been downloaded successfully (ABDB001006_trajectory.xtc)

***
4) **Trajectory visualization**
***

In [14]:
# Show trajectory
try:
    import simpletraj
    view2 = nglview.show_simpletraj(
        nglview.SimpletrajTrajectory(trajectory_filename, structure_filename), gui=True)
    view2._remote_call('setSize', target='Widget', args=['800px','600px'])
    view2
except ImportError:
    import mdtraj as md, os as _os, py3Dmol
    from IPython.display import display as _display

    _t = md.load(trajectory_filename, top=structure_filename)
    _stride = max(1, _t.n_frames // 100)
    _t_sub = _t[::_stride]
    print(f'{_t.n_frames} frames → animating {_t_sub.n_frames} (stride {_stride})')

    _traj_pdb = _os.path.splitext(trajectory_filename)[0] + '_traj.pdb'
    _t_sub.save_pdb(_traj_pdb)
    with open(_traj_pdb) as _f:
        _pdb_content = _f.read()

    view2 = py3Dmol.view(width=800, height=600)
    view2.addModelsAsFrames(_pdb_content)
    view2.setStyle({'stick': {}})
    view2.zoomTo()
    view2.animate({'loop': 'forward', 'reps': 0, 'interval': 100})
    view2.show()

100190 frames → animating 101 (stride 1001)

***
5) **Trajectory analyses** (MDDB)
***

In [ ]:
# Retrieve the MDDB accession from the specific ABDB compound
mddb_entry_request = api_url + f'/compounds/{accession}'

# Query the API
with urllib.request.urlopen(mddb_entry_request) as response:
    parsed_response = json.loads(response.read().decode("utf-8"))

# Print link to MDDB MD analyses
compound_title = f"{parsed_response['Family'].title()}-{parsed_response['Compound'].title()} ({parsed_response['Charge']})"
mddb_link = f"MDDB (MDposit) link to MD analyses: [link={mddb_web}/#/id/{parsed_response['accession']}]{mddb_web}/#/id/{parsed_response['accession']}[/link]"
print(Panel(f"[bold blue]{compound_title}[/bold blue]\n\n{mddb_link}"))

<a id="qm"></a>
## QM data from AB-DB

**Downloading** and **exploring** **QM data** from the **AB-DB** entries

1) Download the **QM-optimized** structure and compare it against the original one
2) **AMBER force-field parameters** generated from the **QM calculations**
3) **Geometry optimization** and **Single-point energy calculation** data (ioChem-BD)

***
1) Download the **QM-optimized** structure and compare it against the original one
***

In [ ]:
qm_query = f"{api_url}/compounds/{accession}/files/qm_optimized.sdf"

# Download the file with an arbitrary name
qm_filename = f'{accession}_qm_optimized.sdf'

# Query the API
urllib.request.urlretrieve(qm_query, qm_filename)

if exists(qm_filename):
    print(f'File has been downloaded successfully ({qm_filename})')

In [ ]:
view = nglview.show_structure_file(qm_filename)
view._remote_call('setSize', target='Widget', args=['','600px'])
view

In [ ]:
# Show structures: protein, ligand and protein-ligand complex
view1 = nglview.show_structure_file(structure_filename)
view1._remote_call('setSize', target='Widget', args=['550px','400px'])
view1.camera='orthographic'
view1
view2 = nglview.show_structure_file(qm_filename)
view2.add_representation(repr_type='ball+stick')
view2._remote_call('setSize', target='Widget', args=['550px','400px'])
view2.camera='orthographic'
view2
ipywidgets.HBox([view1, view2])

***
2) **AMBER force-field parameters** generated from the **QM calculations**
***

In [ ]:
# AMBER frcmod
ff_frcmod_query = f"{api_url}/compounds/{accession}/files/ff_mol.frcmod"

# Download the file with an arbitrary name
ff_frcmod_filename = f'{accession}_ff.frcmod'

# Query the API
urllib.request.urlretrieve(ff_frcmod_query, ff_frcmod_filename)

if not exists(ff_frcmod_filename):
    print(f'File has not been downloaded successfully ({ff_frcmod_filename}). Please check!')

# AMBER prep file
ff_prep_query = f"{api_url}/compounds/{accession}/files/ff_mol.prep"

# Download the file with an arbitrary name
ff_prep_filename = f'{accession}_ff.prep'

# Query the API
urllib.request.urlretrieve(ff_prep_query, ff_prep_filename)

if not exists(ff_prep_filename):
    print(f'File has not been downloaded successfully ({ff_prep_filename}). Please check!')

frcmod_url = f"/files/{ff_frcmod_filename}"
prep_url = f"/files/{ff_prep_filename}"

print(
    Panel(
        f"[bold]AMBER frcmod file:[/bold]\n\n[link={frcmod_url}]{ff_frcmod_filename}[/link]",
        border_style="grey37"
    ),
    Panel(
        f"[bold]AMBER prep file:[/bold]\n\n[link={prep_url}]{ff_prep_filename}[/link]",
        border_style="grey37"
    )
)

***
3) **Geometry optimization** and **Single-point energy calculation** data (ioChem-BD)
***

In [ ]:
# Retrieve the MDDB accession from the specific ABDB compound
mddb_entry_request = api_url + f'/compounds/{accession}'

# Query the API
with urllib.request.urlopen(mddb_entry_request) as response:
    parsed_response = json.loads(response.read().decode("utf-8"))

family = parsed_response['Family']
compound = parsed_response['Compound']
charge = parsed_response['Charge']

ioChem_url = f"{iochem_bd_web}/simple-search?query=%22{family}%20{compound}%20{charge}%22"

print(
    Panel(
        f"[bold]ioChem-BD QM entries:[/bold]\n\n[link={ioChem_url}]{ioChem_url}[/link]",
        border_style="grey37"
    )
)

***
<a id="questions"></a>

## Questions & Comments

Questions, issues, suggestions and comments are really welcome!

* GitHub issues:
    * [https://github.com/bioexcel/biobb](https://github.com/bioexcel/biobb)